### PR TITLE
Use local material on the fs for test-drive

### PR DESCRIPTION
**Pull request by ibnc**
See https://github.com/gocd/gocd/issues/6469

### CODE REVIEW

**Comment by ibnc** [comment]
Do not merge please

**Comment by ibnc** [comment]
Artifacts from this pipeline can be used for verification: [here](https://build.gocd.org/go/tab/build/detail/gocd-trial-installers-test/5/package/1/package)

**Comment by ibnc** [comment]
@marques-work @kierarad when one of you have time, would you mind reviewing this PR?

**Comment by marques-work** [comment]
@ibnc sure, I’ll take a look.

**Comment by marques-work** [comment]
So sorry, this dropped off my radar for a bit. One thing I may play around with before merging is cloning as a bare repo. I'll look at that.

**Comment by marques-work** [comment]
@ibnc I fixed the packaging that broke after we changed our zip installers, and just tested cloning a bare repository. Merging now.

**Pull request merged**
